import { Open_Sans, Playfair_Display } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import BootstrapClient from "@/components/BootstrapClient/BootstrapClient";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  // subsets: ["latin", "thai"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  // subsets: ["latin", "thai"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="th">
      <body className={`${openSans.variable} ${playfairDisplay.variable}`}>
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
